---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Introduction
- type: heading
  label: Quick Usage
- type: heading
  label: Installation
- type: heading
  label: Tools
- type: heading
  label: Execution
- type: heading
  label: Known Issues
- type: heading
  label: FAQs
- type: heading
  label: Credits
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: yarn add -D vuepress
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn run build
